### ISSUE TITLE
Unable to compile: 'progman_ini' undeclared

### ISSUE THREAD

**Issue by Commenter25** [jcs/progman#10]
Trying to compile on Arch, unsure if this is something I need to fix on my end. 
```
cc -O2 -Wall -Wunused -Wunused -Wmissing-prototypes -Wstrict-prototypes -Wpointer-sign `pkg-config --cflags x11 xft xext xpm gdk-pixbuf-xlib-2.0` -DUSE_GDK_PIXBUF -DHIDPI=1   -c -o parser.o parser.c
parser.c: In function 'open_ini':
parser.c:53:24: error: 'progman_ini' undeclared (first use in this function)
   53 |         ini = fmemopen(progman_ini, sizeof(progman_ini), "r");
      |                        ^~~~~~~~~~~
parser.c:53:24: note: each undeclared identifier is reported only once for each function it appears in
make: *** [<builtin>: parser.o] Error 1
```

**Comment by jcs** [comment]
You probably don't have `xxd` installed

**Comment by Commenter25** [comment]
Nope, that can't be it. I had to install it to get to this point, it would straight up say `xxd: command not found` :p

**Comment by jcs** [comment]
Yeah but it probably executed previously and output nothing to `progman_ini.h`, which is why `progman_ini` is not defined.  Try `rm progman_ini.h` and `make` again now that it's installed.

**Comment by Commenter25** [comment]
Ah, that fixed it! I probably should've thought of that :/ Thanks for the help, got it up and running now with no issues! Gonna have fun with this ;D
