### ISSUE TITLE
Loading a theme

### ISSUE THREAD

**Issue by woomia** [jcs/progman#15]
How do you load a theme? I tried progman -c /home/foo/hotdogstand.ini and while the theme works there is no root menu and button 2 doesn't launch an xterm. Am I missing something simple?

**Comment by jcs** [comment]
No, using `-c` replaces the config file so it's not loading all of the other things from your normal config like menus and button actions.

I guess this could be improved with an "include" directive or something in the ini parser but it may just be easier to copy and paste the theme colors into your regular config.

**Comment by woomia** [comment]
Thank you!
