### ISSUE TITLE
Make it like program manager proper

### ISSUE THREAD

**Issue by darkhog** [jcs/progman#20]
Yes, including the launcher and program groups, etc. Because right now it looks like nothing more but a reskin of IceWM (I know it's different codebase, I am just describing how it looks from the end user's perspective). But if it looks like program manager proper and not just a Windows 3.1-like window dressing (which can be had in KDE or other environments that have easy way to make custom window decorations), I can imagine myself using it.

//edit: I'm basically talking about this part: 
![Program_Manager](https://github.com/jcs/progman/assets/1531474/5e2f4eab-5ab3-4395-bda5-6fe268c82efc)

**Comment by darkhog** [comment]
Why bother making it if you're not willing to do it properly?

**Comment by mrshll** [comment]
I imagine they made it the way they wanted and don't care if you use it or not.
