### ISSUE TITLE
--replace flag

### ISSUE THREAD

**Issue by arodland** [jcs/progman#21]
The doc is [ICCCM](https://www.x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html), but the best reference is [the FVWM source](https://github.com/fvwmorg/fvwm3/blob/main/fvwm/icccm2.c#L49) — it's not that bad.

Instead of the current "try to play with the root window and error if X won't let us", the compliant way to go is:

1. Use `XGetSelectionOwner` to see if there's already a window manager.
2. If there is already a WM and the user didn't ask for `--replace`, exit with a nice message.
3. If there's no existing WM, or the user wants you to replace it, use `XSetSelectionOwner` to acquire the WM selection.
4. If there was an existing WM, it will exit upon losing the selection, but you have to wait for it to do so, by awaiting a `DestroyNotify` on the window that `XGetSelectionOwner` gave you in step 1.
5. Congratulations, you are now the window manager.

The selection that you want to check for or acquire is `WM_Sn`, where `n` is replaced with the screen number (i.e. `WM_S0` almost always, because nobody actually uses X screens post-2000, even if they have multiple monitors).

**Comment by jcs** [comment]
I await your pull request

**Comment by arodland** [comment]
Had I gotten a less dickish response, I probably would have written one.
