### ISSUE TITLE
Graphical glitch on Gentoo

### ISSUE THREAD

**Issue by wallace-aph** [jcs/progman#3]
I've been using progman on FreeBSD, where it works great, but on an up-to-date Gentoo install, there's a weird graphical glitch in the right corner: https://0x0.st/iOAl.png (the screenshot was before 127b5dafdff6cfa3032b6d42c00103723797ab3e, but it's still an issue on the latest commit. Also tested some commits from last week, and the glitch is still there). Any ideas on what's causing that? I can do testing if needed.

**Comment by jcs** [comment]
Can you reproduce it as of e2287a3?

**Comment by wallace-aph** [comment]
That fixed it, thanks!

Been loving using progman, it's like fvwm without all the extra cruft. Keep it up.
