### ISSUE TITLE
Packaging a release

### ISSUE THREAD

**Issue by lordfeck** [jcs/progman#4]
Greetings,

I love that this exists. I would also love to package it for a GNU/Linux OS, but the [contribution guidelines](https://github.com/void-linux/void-packages/blob/master/CONTRIBUTING.md) require all submissions to be in a downloadable release of the source code. This makes life easy for the source packager, as all it needs to do is download the release source file and run the configured build instructions.

With that said, would you mind creating a release of the source code and packaging it in a suitable format (like tgz)? GH seems to allow hosting of release packages, though it isn't something I have direct experience doing.

Much appreciated,
Lord Feck.

**Comment by jcs** [comment]
Now that the Gtk dependency has been dropped, I've tagged a v1.0 release.  It can be downloaded at the usual GitHub archive URL:

https://github.com/jcs/progman/archive/v1.0.tar.gz

**Comment by lordfeck** [comment]
Many thanks @jcs
