### ISSUE TITLE
Fix issue with Firefox link tooltips

### ISSUE THREAD

**Issue by jcs** [jcs/progman#5]
When mousing over a link in Firefox that has a title attribute, the tooltip will pop up showing its URL as usual, but will instantly disappear.  Using progman with debugging enabled doesn't show any event for the tooltip appearing, and then the frame window gets an `EnterEvent`.

**Comment by Pelle-B** [comment]
I thinkthis could  be a Firefox-bug. There is a similar problem with CTWM.
