### ISSUE TITLE
Cant compile (Q4OS Trinity/Debian 10)

### ISSUE THREAD

**Issue by Freddie-Green** [jcs/progman#7]
When i try to compile it i get this error, pleae fix this

q4os@q4os-pc:~$ cd progman-master
q4os@q4os-pc:~/progman-master$ make
cc -O2 -Wall -Wunused -Wunused -Wmissing-prototypes -Wstrict-prototypes -Wpointer-sign `pkg-config --cflags x11 xft xext xpm gdk-pixbuf-xlib-2.0` -DUSE_GDK_PIXBUF -DHIDPI=1   -c -o atom.o atom.c
/bin/sh: 1: pkg-config: not found
atom.c:23:10: fatal error: err.h: No such file or directory
 #include <err.h>
          ^~~~~~~
compilation terminated.
make: *** [<builtin>: atom.o] Error 1
q4os@q4os-pc:~/progman-master$

**Comment by Freddie-Green** [comment]
Q4OS is based on Debian 10

**Comment by jcs** [comment]
Install `libbsd`
