### ISSUE TITLE
Large buttons etc despite commenting out -DHIDPI

### ISSUE THREAD

**Issue by Pelle-B** [jcs/progman#9]
I commented out -DHIDPI (whatever that is), in the makefile `# use 2x icons, borders, fonts for HiDPI displays; optional
#CFLAGS+=	-DHIDPI=1`

Tried it on two computers with two distributions, yet I get  (without and with progman.ini in ~/.config/progman) very large buttons, fonts and titlebar. It does not really look like on the screenshot...

**Comment by jcs** [comment]
Did you `make clean` after changing that?

**Comment by Pelle-B** [comment]
It is the fonts. I think the Microsoft bit confused the system. `font = Sans:bold:size=10
iconfont = Sans:size=8` works well, especially when title padding is reduced from 6 to 3.

I like Progman!
